/**
 * `form-agent metrics` command handler (P7-R12, P7-R13, P7-R15, P7-R16, P7-R17).
 *
 * Operationally read-only: no browser/network/LLM, no claim, no authorization
 * or rate mutation, no draft provider, no receipt/snapshot mutation, and NO
 * metrics_events row generated by querying. The accepted `FormAgentDatabase`
 * open lifecycle is reused (idempotent migration catalog = the ONE permitted
 * schema-maintenance write).
 *
 *   form-agent metrics summary [--since <ISO8601>] [--until <ISO8601>]
 *   form-agent metrics export --format json|csv [--since <ISO8601>] [--until <ISO8601>]
 *
 * There is deliberately no `metrics summary --json`; `export --format json` is
 * the single machine-readable JSON contract.
 */

import { FormAgentDatabase, type DatabaseOptions } from '../db/database.ts';
import { ExitCodes } from './exit-codes.ts';
import type { CliContext } from './index.ts';
import { systemMetricsClock } from '../metrics/clock.ts';
import { parseIsoTimestamp, formatTimestamp } from '../metrics/time.ts';
import {
  readAggregates,
  MetricsSourceUnavailableError,
  type MetricsRange,
  type MetricsRangeOutput,
} from '../metrics/aggregate.ts';
import { buildMetricsExport, formatMetricsCsv, formatMetricsHuman } from '../metrics/format.ts';

type MetricsSubcommand = 'summary' | 'export';
type MetricsFormat = 'json' | 'csv';

interface ParsedMetricsArgs {
  subcommand: MetricsSubcommand;
  format: MetricsFormat | undefined;
  sinceMs: number | null;
  untilMs: number | null;
}

type ParsedResult =
  | { ok: true; value: ParsedMetricsArgs }
  | { ok: false; error: string };

function takeTimestamp(name: string, raw: string): { ok: true; ms: number } | { ok: false; error: string } {
  const ms = parseIsoTimestamp(raw);
  if (ms === null) {
    return {
      ok: false,
      error: `${name} must be a full RFC3339 timestamp with an explicit timezone (Z or ±HH:MM)`,
    };
  }
  return { ok: true, ms };
}

function parseMetricsArgs(args: string[]): ParsedResult {
  const subcommand = args[0];
  if (subcommand !== 'summary' && subcommand !== 'export') {
    return { ok: false, error: 'metrics requires a subcommand: summary or export' };
  }

  let format: MetricsFormat | undefined;
  let sinceRaw: string | undefined;
  let untilRaw: string | undefined;

  for (let i = 1; i < args.length; i++) {
    const arg = args[i] as string;
    if (arg === '--since' || arg === '--until' || arg === '--format') {
      const next = args[i + 1];
      if (next === undefined || next.startsWith('--')) {
        return { ok: false, error: `${arg} requires a value` };
      }
      if (arg === '--since') sinceRaw = next;
      else if (arg === '--until') untilRaw = next;
      else {
        if (next !== 'json' && next !== 'csv') {
          return { ok: false, error: '--format must be json or csv' };
        }
        format = next;
      }
      i += 1;
    } else if (
      arg.startsWith('--since=') ||
      arg.startsWith('--until=') ||
      arg.startsWith('--format=')
    ) {
      const eq = arg.indexOf('=');
      const name = arg.slice(0, eq);
      const value = arg.slice(eq + 1);
      if (value === '') return { ok: false, error: `${name} requires a non-empty value` };
      if (name === '--since') sinceRaw = value;
      else if (name === '--until') untilRaw = value;
      else {
        if (value !== 'json' && value !== 'csv') {
          return { ok: false, error: '--format must be json or csv' };
        }
        format = value;
      }
    } else {
      // Unknown flags (including --json) and extra positionals never echo raw content.
      return { ok: false, error: 'unknown flag or argument' };
    }
  }

  if (subcommand === 'summary' && format !== undefined) {
    return { ok: false, error: '--format is only valid for metrics export' };
  }
  if (subcommand === 'export' && format === undefined) {
    return { ok: false, error: 'metrics export requires --format json|csv' };
  }

  let sinceMs: number | null = null;
  let untilMs: number | null = null;
  if (sinceRaw !== undefined) {
    const parsedSince = takeTimestamp('--since', sinceRaw);
    if (!parsedSince.ok) return { ok: false, error: parsedSince.error };
    sinceMs = parsedSince.ms;
  }
  if (untilRaw !== undefined) {
    const parsedUntil = takeTimestamp('--until', untilRaw);
    if (!parsedUntil.ok) return { ok: false, error: parsedUntil.error };
    untilMs = parsedUntil.ms;
  }
  if (sinceMs !== null && untilMs !== null && sinceMs >= untilMs) {
    return { ok: false, error: '--since must be earlier than --until' };
  }

  return { ok: true, value: { subcommand, format, sinceMs, untilMs } };
}

export interface HandleMetricsOptions {
  /** Test seam: override the accepted database-open lifecycle. */
  openDatabase?: (options: DatabaseOptions) => FormAgentDatabase;
}

export async function handleCmdMetrics(
  args: string[],
  ctx: CliContext,
  options: HandleMetricsOptions = {},
): Promise<number> {
  const parsed = parseMetricsArgs(args);
  if (!parsed.ok) {
    ctx.logger.error(parsed.error);
    return ExitCodes.USAGE;
  }
  const { subcommand, format, sinceMs, untilMs } = parsed.value;

  const openDatabase = options.openDatabase ?? FormAgentDatabase.open;
  let database: FormAgentDatabase;
  try {
    database = openDatabase({
      directory: ctx.config.database.directory,
      filename: ctx.config.database.filename,
    });
  } catch {
    ctx.logger.error('metrics database is unavailable');
    return ExitCodes.ERROR;
  }

  try {
    const range: MetricsRange = { sinceMs, untilMs };
    let aggregates;
    try {
      aggregates = readAggregates(database, range);
    } catch (err) {
      if (err instanceof MetricsSourceUnavailableError) {
        ctx.logger.error('metrics event store is unavailable');
        return ExitCodes.ERROR;
      }
      ctx.logger.error('metrics aggregation failed');
      return ExitCodes.ERROR;
    }

    const clock = ctx.metricsClock ?? systemMetricsClock;
    const rangeOutput: MetricsRangeOutput = {
      since: sinceMs === null ? null : formatTimestamp(sinceMs),
      until: untilMs === null ? null : formatTimestamp(untilMs),
    };

    if (subcommand === 'summary') {
      process.stdout.write(`${formatMetricsHuman(aggregates, rangeOutput)}\n`);
      return ExitCodes.SUCCESS;
    }

    if (format === 'csv') {
      process.stdout.write(`${formatMetricsCsv(aggregates)}\n`);
      return ExitCodes.SUCCESS;
    }

    const generatedAt = new Date(clock.wallNowMs()).toISOString();
    const document = buildMetricsExport(aggregates, rangeOutput, generatedAt);
    process.stdout.write(`${JSON.stringify(document, null, 2)}\n`);
    return ExitCodes.SUCCESS;
  } finally {
    database.close();
  }
}
